name: validator
version: 0.0.8
author: Karan Goel <karan@goel.io>
description: String validation and sanitization for Dart.
homepage: https://github.com/karan/validator.dart
environment:
  sdk: '>=1.20.1'
documentation: https://github.com/karan/validator.dart
dependencies:
  unittest: any
